Grupp 2/Controllers/EducationController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Data;
using Data.Models;

namespace Grupp_2.Controllers
{
    public class EducationController : Controller
    {
        private Datacontext db = new Datacontext();

        public ActionResult Index()
        {
            return View(db.Educations.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EduID,Title")] Education education)
        {
            Education tempEdu = db.Educations.Where(x => x.Title == education.Title).FirstOrDefault();

            if (tempEdu == null)
            {
                if (ModelState.IsValid)
                {
                    db.Educations.Add(education);
                    db.SaveChanges();
                    return RedirectToAction("Create");
                }
            }

            else if (tempEdu.Title.ToLower() == education.Title.ToLower())
            {
                TempData["alertMessage"] = "Denna utbildning existerar redan i systemet!";
                return RedirectToAction("Create");
            }
            return View(education);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grupp 2/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Data.Models;
using Data.Respositories;
using Grupp_2.Models;

namespace Grupp_2.Controllers
{
    public class MessageController : Controller
    {
        private Datacontext db = new Datacontext();
        private UserRespository userRespository = new UserRespository();
        private MessageRepository messageRepository = new MessageRepository();

        public ActionResult Index()
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            User user = userRespository.GetUserByEmail(loggedInUserMail);
            ViewBag.userID = user.UserID;

            var UserMessages = messageRepository.GetUserMessagesByUserID(user.UserID);
            List<MessagesViewModel> listMsgViewModels = new List<MessagesViewModel>();

            //Skapar en ny message-viewmodel för varje meddelande som finns i databasen.
            foreach (var item in UserMessages)
            {
                var MsgViewModel = new MessagesViewModel
                {
                    Reciver = user.UserID,
                    Read = item.Read,
                    Sender = item.Sender,
                    MessageID = item.MessageID
                };
                var msg = messageRepository.GetMessageByMessageID(item.MessageID);
                MsgViewModel.Content = msg.Content;
                listMsgViewModels.Add(MsgViewModel);

            }

            return View(listMsgViewModels);
        }

        public ActionResult MarkAsRead(int id)
        {
            messageRepository.MarkAsRead(id);
            return RedirectToAction("Index");
        }
        public ActionResult MarkAsUnRead(int id)
        {
            messageRepository.MarkAsUnRead(id);
            return RedirectToAction("Index");
        }


        public ActionResult MarkAllAsRead(int userID)
        {
            messageRepository.MarkAllAsRead(userID);
            return RedirectToAction("Index");
        }

        public ActionResult Create(int id)
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            User userSend = userRespository.GetUserByEmail(loggedInUserMail);
            string name = null;
            if (userSend != null)
            {
                name = userSend.Firstname + " " +  userSend.Lastname;
            }

            var UserRec = userRespository.GetUserByUserID(id);
            var model = new MessagesViewModel
            {
                Sender = name,
                Reciver = id,
                ReciverName = UserRec.Firstname + " " + UserRec.Lastname
             };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MessageID,Content")] Message message) //denna körs aldrig, går t api ist
        {
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(message);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("Message/Delete/DeleteAjax/{id}")]
        public ActionResult DeleteAjax(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grupp 2/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Data;
using Data.Models;
using Data.Respositories;
using Grupp_2.Models;

namespace Grupp_2.Controllers
{
    public class ProjectController : Controller
    {
        private Datacontext db = new Datacontext();
        private UserRespository userRespository = new UserRespository();
        private ProjectRespository ProjectRespository = new ProjectRespository();

        public ActionResult Insert(int id)
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            User user = userRespository.GetUserByEmail(loggedInUserMail);

            ProjectRespository.AddNewProjectUser(id, user.UserID);

            return RedirectToAction("ProjectVM");
        }

        public ActionResult Remove(int id)
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            User user = userRespository.GetUserByEmail(loggedInUserMail);
            var tempProjekt = ProjectRespository.GetProjectUsersByProjectIDAndUserID(id, user.UserID);

            ProjectRespository.DeleteProjectUser(tempProjekt);

            return RedirectToAction("ProjectVM");
        }

        public ActionResult Create()
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            ViewBag.Creator = new SelectList(db.Users.Where(u => u.Email == loggedInUserMail).ToList(), "UserID", "Firstname");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectID,Titel,Description,Creator")] Project project)
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            ViewBag.Creator = new SelectList(db.Users.Where(u => u.Email == loggedInUserMail).ToList(), "UserID", "Firstname");
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrWhiteSpace(project.Description) && !string.IsNullOrWhiteSpace(project.Titel))
                {
                    if (!ProjectRespository.TitelExists(project.Titel))
                    {

                        ProjectRespository.AddNewProject(project);

                        return RedirectToAction("ProjectVM");

                    }
                    else
                    {
                        TempData["alertMessage"] = "Finns redan ett projekt med den titeln!";
                        return View(project);
                    }
                }

                else
                {
                    TempData["alertMessage"] = "Fyll i titel samt beskrivning!";
                    return View(project);

                }
            }
            ViewBag.Creator = new SelectList(userRespository.GetAllUsers(), "UserID", "Firstname", project.Creator);
            return View(project);
        }

        public ActionResult Edit(int? id) //ska denna selectlisten (ENDAST EN CREATOR) brytas? behöver ha den i en lista
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            string loggedInUserMail = User.Identity.Name.ToString();
            ViewBag.Creator = new SelectList(db.Users.Where(u => u.Email == loggedInUserMail).ToList(), "UserID", "Firstname");
            return View(project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectID,Titel,Description,Creator")] Project project)
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            ViewBag.Creator = new SelectList(db.Users.Where(u => u.Email == loggedInUserMail).ToList(), "UserID", "Firstname");

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(project.Description) && !string.IsNullOrWhiteSpace(project.Titel))
                {
                    if (!ProjectRespository.TitelExists(project.Titel))
                    {

                        db.Entry(project).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("ProjectVM");
                    }
                    else
                    {
                        TempData["alertMessage"] = "Finns redan ett projekt med den titeln!";
                        return View(project);
                    }
                }

                else
                {
                    TempData["alertMessage"] = "Fyll i titel samt beskrivning!";
                    return View(project);

                }
            }



            ViewBag.Creator = new SelectList(userRespository.GetAllUsers(), "UserID", "Firstname", project.Creator);
            return View(project);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectRespository.DeleteProjectById(id);
            return RedirectToAction("ProjectVM");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ProjectVM()
        {
            string loggedInUserMail = User.Identity.Name.ToString();
            User user = userRespository.GetUserByEmail(loggedInUserMail);

            if (user != null)
            {
                int userId = user.UserID;
                ViewBag.Id = userId;
            }
            List<Project> projects = new List<Project>();

            projects = ProjectRespository.GetAllProjectIncludeUser();
            List<ProjectsViewModel> ProjectViews = new List<ProjectsViewModel>();
            
            using (var context = new Datacontext())
            {
                foreach (var item in projects)
                {
                    ProjectsViewModel ProjectsViewModel = null;
                    //Om användare inte är inloggad, namnger projektets skapare som anonym användare
                    if (user == null && item.User.PrivateProfile == true)
                    {
                        ProjectsViewModel = new ProjectsViewModel(item.Creator, item.Titel, item.Description, item.ProjectID);
                    }
                    //Displayar allas namn
                    else
                    {
                        string creatorname = item.User.Firstname + " " + item.User.Lastname;
                        ProjectsViewModel = new ProjectsViewModel(creatorname, item.Creator, item.Titel, item.Description, item.ProjectID);
                    }
                    var projusers = ProjectRespository.GetProjectUsersByProjectID(item.ProjectID);
                    List<string> namn = new List<string>();
                    List<string> namnNonHidden = new List<string>();

                    //Separerar namnlistor i privata och ickeprivata namn
                    foreach (var projects_Users in projusers)
                    {
                        var anv = context.Users.Where(u => u.UserID == projects_Users.UserID).ToList();

                        foreach (var anvItem in anv)
                        {
                            namn.Add(anvItem.Firstname);
                            if (anvItem.PrivateProfile == false)
                            {
                                namnNonHidden.Add(anvItem.Firstname);
                            }
                        }
                    }
                    ProjectsViewModel.Users = namn;
                    ProjectsViewModel.UsersNotHidden = namnNonHidden;

                    ProjectViews.Add(ProjectsViewModel);
                }

                //ViewBag med alla projektId som inloggade användaren är med i
                if (user != null)
                {
                    var userIdCommon = ProjectRespository.GetProjectUsersFromUserID(user.UserID);
                    List<string> projIds = new List<string>();
                    foreach (var item in userIdCommon)
                    {
                        projIds.Add(item.ProjectID.ToString());
                    }
                    ViewBag.Projects = projIds;
                }
                return View(ProjectViews);
            }
        }
    }
}

Grupp 2/Controllers/SkillController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Data;
using Data.Models;

namespace Grupp_2.Controllers
{
    public class SkillController : Controller
    {
        private Datacontext db = new Datacontext();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SkillID,Title")] Skill skill)
        {
            Skill tempSkill = db.Skills.Where(x => x.Title == skill.Title).FirstOrDefault();

            if (tempSkill == null)
            {
                if (ModelState.IsValid)
                {
                    db.Skills.Add(skill);
                    db.SaveChanges();
                    return RedirectToAction("Create");
                }
            }
            else if (tempSkill.Title.ToLower() == skill.Title.ToLower())
            {
                TempData["alertMessage"] = "Denna färdighet existerar redan i systemet!";
                return RedirectToAction("Create");
            }
            return View(skill);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grupp 2/Views/CV/CreateCVVM.cshtml
@model Grupp_2.Models.CreateCVViewModel

@{
    ViewBag.Title = "Din CV-sida";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (null != TempData["alertMessage"])
{
    <script type="text/javascript">
    alert('@TempData["alertMessage"]');
    </script>
}
@using (Html.BeginForm("Upload", "Cv", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <div>
        <h3>Din profilbild:</h3>
        <br />
        <img src="@ViewBag.Path" alt="Profilbild kunde inte laddas" style="border-radius: 50%" , width="300px" />
    </div>
    <br />
    <div style="display: inline-block">
        Välj en fil: <input type="file" name="fileUpload" accept="image/png, image/gif, image/jpeg" />

        <input type="submit" value="Ladda upp" />
    </div>
}
<br />
<br />

<p id="antalVisningar">Antal visningar:  </p>


    @using (Html.BeginForm("UpdateCvVm", "Cv", FormMethod.Post))
    {
        <h4>Tillagda Utbildningar i ditt cv:</h4>
        <ul>
            @foreach (var item in Model.Educations)
            {
                <li>
                    @item.Title   <input type="submit" name="actionType" value="Ta bort utbildning @item.Title" />
                </li>

            }
        </ul>

        <hr />

        <h4>Tillagda Arbetserfarenheter i ditt cv:</h4>
        <ul>
            @foreach (var item in Model.Work_Experiences)
            {
                <li>
                    @item.Titel <input type="submit" name="actionType" value="Ta bort arbete @item.Titel" />
                </li>

            }
        </ul>

        <hr />

        <h4>Tillagda färdigheter i ditt cv:</h4>
        <ul>
            @foreach (var skills in Model.Skills)
            {
                <li>
                    @skills.Title <input type="submit" name="actionType" value="Ta bort erfarenhet @skills.Title"  />
                </li>

            }
        </ul>

        <hr />

        <tr>
            <td> Lägg till en ny färdighet i ditt cv: </td>
            <td>


                @Html.DropDownList("MySkills", (IEnumerable
               <SelectListItem>)ViewData["DBMySkills"])

                <input type="submit" name="actionType" value="Lägg till färdighet på ditt cv" class="btn btn-primary" />




            </td>

        </tr>

        <hr />

        <tr>
            <td> Lägg till en ny Arbets erfarenhet i ditt cv: </td>
            <td>
                @Html.DropDownList("WorkExp", (IEnumerable
               <SelectListItem>)ViewData["DBMyWorkExp"])


                <input type="submit" name="actionType" value="Lägg till arbete i cvet" class="btn btn-primary" />

            </td>


        </tr>
        <hr />

        <tr>
            <td> Lägg till en ny Utbildning i ditt cv: </td>
            <td>
                @Html.DropDownList("MyEducations", (IEnumerable
               <SelectListItem>)ViewData["DBMyEducations"])

                <input type="submit" name="actionType" value="Lägg till Utbildning i cvet" class="btn btn-primary"/>
            </td>
        </tr>

    }

<hr />
<p> Saknas din erfarenhet? Lägg till i vår databas </p>
<h4>Lägg till nya objekt i databasen:</h4>
<br />
    <p>
        @Html.ActionLink("Lägg till ny Färdighet", "Create", "Skill")
        @Html.ActionLink("Lägg till nytt Arbete", "Create", "Work_Experience")
        @Html.ActionLink("Lägg till ny Utbildning", "Create", "Education")
    </p>

    <table class="table">
        <tr>
            <th>
                Skapare

        </th>
        <th>
            Titel
        </th>
        <th>
            Beskrvining
        </th>
    </tr>
    @using (Html.BeginForm("CreateCVVM", "Cv", FormMethod.Post))
    {
        foreach (var item in Model.Projects)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Firstname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                @if (item.Creator != ViewBag.Id)
                {
                    <td>
                        <input type="button" value="Gå ur projekt" onclick="location.href='@Url.Action("Remove", "Cv", new { id = item.ProjectID })'" />
                    </td>
                }
                @if (item.Creator == ViewBag.Id)
                {
                    <td>

                        @Html.ActionLink("Edit", "Edit", "Project", new { id = item.ProjectID }, null) |
                        @Html.ActionLink("Delete", "Delete", "Project", new { id = item.ProjectID }, null)
                    </td>
                }
            </tr>

            }



        }






        @section Scripts {

            <script>

                $.get('/api/GetApiVisning/', function (data) {
                    $('#antalVisningar').append(data);
                })

            </script>
            @Scripts.Render("~/bundles/jqueryval")
        }

Grupp 2/Views/CV/ShowUserCV.cshtml
@model Grupp_2.Models.CreateCVViewModel
@{
    ViewBag.Title = "ShowCVVM";
    Layout = null;
}

<body>
    <div class="container body-content">

        <h2>Cv för @Model.User</h2>
        <div>
            <h3>Profilbild:</h3>
            <img src=@Model.Imgpath alt="Profilbild kunde inte laddas" style="border-radius: 50%" , width="300px" />
        </div>

        <br />
        <h4>Kontaktinformation:</h4>
        <p>Adress: @Model.Adress</p>
        <p>Epost: @Model.Email</p>
        <p>Github namn: <p id="gitNamn">@Model.Github </p> </p>
        <br />

        <hr />

        <h4>Utbildningar:</h4>
        <ul>
            @foreach (var item in Model.Educations)
            {
                <li>
                    @item.Title
                </li>

            }
        </ul>

        <hr />

        <h4>Arbetserfarenheter:</h4>
        <ul>
            @foreach (var item in Model.Work_Experiences)
            {
                <li>
                    @item.Titel
                </li>

            }
        </ul>

        <hr />

        <h4>Färdigheter:</h4>
        <ul>
            @foreach (var skills in Model.Skills)
            {
                <li>
                    @skills.Title
                </li>

            }
        </ul>

        <hr />
        <br />

        <h4>Projekt:</h4>
        <table class="table">
            <tr>
                <th>
                    Skapare

                </th>
                <th>
                    Titel
                </th>
                <th>
                    Beskrvining
                </th>
            </tr>
            @foreach (var item in Model.Projects)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Firstname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                </tr>


            }
        </table>

        <hr />
        <div>
            <h3>Hitta liknande personer</h3>
            @using (Html.BeginForm("MatchUser", "Cv", new { id = Model.UserID }, FormMethod.Post))
            {
                <h4>Visa liknande personer:</h4>
                <input type="submit" value="Få upp en liknande" class="btn btn-primary" />

            }


        </div>

        <hr />
        <div>
            <h3>Exportera till XML</h3> 
            <p> Sparas i uploaded files, under grupp 2 i projektmappen</p>
                @using (Html.BeginForm("ExportXML", "Cv", new { id = Model.UserID }, FormMethod.Post))
                {
                    <input type="submit" value="Ladda ner" class="btn btn-primary" />

                }


            </div>

            <h4>Länkade Github repos för användaren</h4>
            <table id="repos" class="table">

                <tr>
                    <th>
                        Skapare

                    </th>
                    <th>
                        Titel
                    </th>
                    <th>
                        Beskrvining
                    </th>
                </tr>



            </table>

        </div>
</body>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script>
    console.log("körs");
    var gitUser = $('#gitNamn').html();
    console.log(gitUser);
    if (gitUser != "") {
        console.log("inne i if");
        $.get('https://api.github.com/users/' + gitUser + '/repos', function (data) {
            console.log(data);
            for (var repo of data) {
                $("#repos").append('<tr><td>' + repo.owner.login + '</td><td>' + repo.full_name + '</td><td>' + repo.description + '</td></tr>');
            }
        })
    }

</script>
@Scripts.Render("~/bundles/jqueryval")

<div>@{Html.RenderAction("Create", "Message", new { id = Model.UserID });} </div>